# Generated by Django 3.2 on 2022-02-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(db_index=True, max_length=32, verbose_name='用户名'),
        ),
    ]
